---
title: "Development and Internal Validation of a Model to Predict Malignancy of Adnexal Masses"
subtitle: "Part 0: Analysis Plan"
author: 
  - "Group D"
date: today
execute: 
  echo: true
  warning: false
format:
  docx:
    reference-doc: ../docs/manuscript/template.docx
    link-citations: true
editor: visual
---

```{r}
#| label: directories
#| include: false

# Run only when using Positron (for compatibility with RStudio project)
# setwd(paste0(getwd(),"/R"))

# Create directories for sub-folders  
inputfolder <- "../data/raw"
psfolder <- "../data/processed"
tempfolder <- "../data/temp"
figfolder <- "../results/output_figures"
tabfolder <- "../results/output_tables"

dir.create(inputfolder, showWarnings = FALSE)
dir.create(psfolder, showWarnings = FALSE)
dir.create(tempfolder, showWarnings = FALSE)
dir.create(figfolder, showWarnings = FALSE)
dir.create(tabfolder, showWarnings = FALSE)
```

```{r}
#| label: load packages
#| include: false

if (!require("pacman", quietly = TRUE)) {
  install.packages("pacman")
}

pacman::p_load(
  tidyverse,  
  readxl,
  pmsampsize,
  table1,
  flextable, 
  officer, 
  gt,         
  report     
)
```

```{r}
#| label: load data
#| include: false

data <- read.delim(
  file.path(inputfolder,"ovarian.txt")
  )

# Assign variable characteristics (labels, type of variable, etc.)
source("scripts/variable_names_raw.R")
```

# Characteristics of the study population

```{r}
#| label: malignancy risk

risk_table <- data %>% group_by(mal) %>% summarize(n = n()) %>% 
  mutate(risk = n/sum(n))

risk_table %>% 
  gt %>% 
  fmt_percent(
    columns = risk,
    decimals = 1
  ) %>%
  cols_label(
    risk = "Risk (%)"
  ) 
```

```{r}
#| label: table 1 

table1 <- table1(
  ~ Age + pershistovca + famhistovca + hormtherapy + pain + Ascites + 
    CA125 + papflow + lesdmax + soldmaxorig + wallreg + Shadows + colscore + 
    nrloculescat + papnr + oncocenter | mal,
  data = data,
  overall = c(left = "Overall"),
  caption = "Table 1. Participant characteristics, grouped by adnexal malignancy status"
)

table1
```

```{r}
#| label: save table 1

# Save as word document:
properties <- prop_section(
  page_size = page_size(
    orient = "landscape",
    width = 8.3, height = 11.7
  ),
  type = "continuous",
  page_margins = page_mar()
)

t1flex(table1) %>%
  save_as_docx(
    path = paste(tabfolder, "/Table1.docx", sep = ""),
    pr_section = properties
  )
```


# Sample Size Estimation

```{r}
pmsampsize(
  type="b", 
  parameters= 6,
  shrinkage=0.9,
  prevalence=risk_table$risk[2],
  cstatistic=0.75
  )
```

{{< pagebreak >}}

# References

::: {#refs}
:::


{{< pagebreak >}}

# Package References

```{r}
#| output: asis
report::cite_packages(session)
```

```{r}
#| include: false

# Run this chunk if you wish to clear your environment and unload packages.

pacman::p_unload(negate = TRUE)

rm(list = ls())
```
